# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cghxj_etxm44CuNNU648k6-ekvEEb0IK
"""

name=input("Enter the student's name: ")
modified_name=name.strip().lower()
dict={'alice':100,'harsh':99,'harry':100,}
b=dict.keys()
if modified_name not in b:
  print('student not found')
else:
  marks=dict[modified_name]
  print(f"{modified_name}'s marks:{marks}")